name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1.41.1
      - name: Install dependencies
        run: cpanm --installdeps --notest .
      - name: Run tests
        run: prove -lv t/
